// import Immutable from 'immutable';

export const Aisles = [
  'produce',
  'bulk',
  'liquor',
  'specialty',
  'spreads',
  'bread',
  'seafood',
  'snacks',
  'meat',
  'dairy',
  'cheese',
  'freezer',
  'baking',
  'cereal',
  'pasta',
  'beans',
  'soup',
  'cleaning',
  'babies',
  'personal',
  'medicine',
  'other',
];

/* eslint quote-props: "off" */
export const AisleDesignations = {
  // prefix catch all adjectives
  'baking': 'baking',
  'frozen': 'freezer',
  'fresh': 'produce',
  'alcohol': 'liquor',
  // regular
  '7up': 'snacks',
  'aceto': 'medicine',
  'advil': 'medicine',
  'agave': 'produce',
  'allergy': 'medicine',
  'applesauce': 'baking',
  'artichoke heart': 'beans',
  'arugula': 'produce',
  'asparagus': 'produce',
  'avocado': 'produce',
  'bacon': 'cheese',
  'baggette': 'specialty',
  'baugette': 'specialty',
  'balsamic': 'pasta',
  'bananas': 'produce',
  'band aid': 'medicine',
  'bandaid': 'medicine',
  'basil': 'baking',
  'bb cr': 'babies',
  'beef broth': 'soup',
  'beef': 'meat',
  'beer': 'snacks',
  'berries': 'produce',
  'berry': 'produce',
  'bleach': 'cleaning',
  'fancy bread': 'specialty',
  'good bread': 'specialty',
  'nice bread': 'specialty',
  'bourbon': 'liquor',
  'broccoli': 'produce',
  'broth': 'soup',
  'brussel sprout': 'produce',
  'buns': 'bread',
  'cabbage': 'produce',
  'caesar': 'pasta',
  'cannellini': 'beans',
  'cantelope': 'produce',
  'carrot': 'produce',
  'cashew': 'bulk',
  'cauliflower': 'produce',
  'celery': 'produce',
  'cereal': 'cereal',
  'chapstick': 'personal',
  'chard': 'produce',
  'cheddar': 'cheese',
  'cheerios': 'cereal',
  'club soda': 'liquor',
  'cognac': 'liquor',
  'fancy cheese': 'specialty',
  'nice cheese': 'specialty',
  'good cheese': 'specialty',
  'cheese': 'cheese',
  'chicken stock': 'soup',
  'chicken': 'meat',
  'chickpeas': 'beans',
  'chilies': 'beans',
  'fresh chives': 'produce',
  'chives': 'baking',
  'chocolate chips': 'baking',
  'ciabatta': 'specialty',
  'cilantro': 'baking',
  'clean': 'cleaning',
  'cocoa': 'baking',
  'coconut': 'baking',
  'cod': 'seafood',
  'coffee': 'baking',
  'condition': 'personal',
  'corn chips': 'snacks',
  'corn meal': 'baking',
  'corn starch': 'baking',
  'corn tortilla': 'bread',
  'cornmeal': 'baking',
  'cornstarch': 'baking',
  'corn': 'produce',
  'cottage': 'dairy',
  'cough': 'medicine',
  'cranberry': 'pasta',
  'crab': 'seafood',
  'fancy crackers': 'specialty',
  'nice crackers': 'specialty',
  'good crackers': 'specialty',
  'party crackers': 'specialty',
  'crackers': 'snacks',
  'cucumber': 'produce',
  'deli': 'specialty',
  'deod': 'personal',
  'detergent': 'cleaning',
  'diaper': 'babies',
  'dill': 'baking',
  'dressing': 'pasta',
  'dry onion': 'soup',
  'dried': 'snacks',
  'dryer': 'cleaning',
  'eggnog': 'dairy',
  'eggs': 'cheese',
  'evaporated': 'baking',
  'extract': 'baking',
  'feta': 'cheese',
  'filters': 'baking',
  'flour tortilla': 'bread',
  'flour': 'baking',
  'food coloring': 'baking',
  'french bread': 'specialty',
  'garbage bag': 'soup',
  'garbanzo': 'beans',
  'garlic': 'produce',
  'ginger': 'baking',
  'goldfish': 'snacks',
  'graham': 'snacks',
  'granola': 'cereal',
  'grapes': 'produce',
  'green beans': 'produce',
  'hamburgers': 'meat',
  'hoagies': 'bread',
  'honey': 'spreads',
  'hot dogs': 'meat',
  'ibuprof': 'medicine',
  'ice cream': 'freezer',
  'icecream': 'freezer',
  'jack': 'cheese',
  'kale': 'produce',
  'ketchup': 'pasta',
  'lemon juice': 'pasta',
  'lemon': 'produce',
  'lettuce': 'produce',
  'light bulb': 'soup',
  'lightbulb': 'soup',
  'lights': 'soup',
  'lime juice': 'pasta',
  'lime': 'produce',
  'listerine': 'personal',
  'lobster': 'seafood',
  'lunchmeat': 'specialty',
  'lunch meat': 'specialty',
  'macaroni': 'pasta',
  'mayo': 'pasta',
  'makeup': 'personal',
  'marshm': 'baking',
  'marsh m': 'baking',
  'medicine': 'medicine',
  'melen': 'produce',
  'melon': 'produce',
  'mexican bl': 'cheese',
  'mint': 'produce',
  'mouthwash': 'personal',
  'mouth wash': 'personal',
  'mozzarella balls': 'specialty',
  'mozzarella': 'cheese',
  'mushrooms': 'produce',
  'mustard': 'pasta',
  'neospo': 'medicine',
  'noodle': 'pasta',
  'nuts': 'bulk',
  'oatmeal': 'cereal',
  'oats': 'cereal',
  'onion dip': 'snacks',
  'onion': 'produce',
  'oranges': 'produce',
  'oregano': 'baking',
  'orzo': 'pasta',
  'pain': 'medicine',
  'pancake': 'cereal',
  'panko': 'soup',
  'paprika': 'baking',
  'parchment': 'soup',
  'parmesan': 'cheese',
  'parsley': 'baking',
  'parsnip': 'produce',
  'pasta': 'pasta',
  'patties': 'meat',
  'peanut oil': 'baking',
  'peanut': 'spreads',
  'pecans': 'bulk',
  'black pepper': 'baking',
  'pepper spice': 'baking',
  'pepper': 'produce',
  'pie': 'freezer',
  'pita': 'specialty',
  'plastic bag': 'soup',
  'plastic wrap': 'soup',
  'poppy': 'baking',
  'poppyseed': 'baking',
  'pork': 'meat',
  'potato chips': 'snacks',
  'potato': 'produce',
  'provalone': 'cheese',
  'provolone': 'cheese',
  'pumpkins': 'produce',
  'pumpkin': 'baking',
  'pull up': 'babies',
  'pullup': 'babies',
  'quinoa': 'pasta',
  'radish': 'produce',
  'raisen': 'snacks',
  'raison': 'snacks',
  'ramen': 'soup',
  'razor': 'personal',
  'rice': 'bulk',
  'rigatoni': 'pasta',
  'roast': 'meat',
  'root': 'snacks',
  'rosemary': 'baking',
  'salad ingredients': 'produce',
  'salami': 'meat',
  'salmon': 'seafood',
  'salsa': 'produce',
  'salt': 'baking',
  'sausage': 'meat',
  'scallions': 'produce',
  'shallots': 'produce',
  'shampoo': 'personal',
  'shaving': 'personal',
  'shrimp': 'seafood',
  'sour cream': 'cheese',
  'spaghetti': 'pasta',
  'sparkling water': 'snacks',
  'spice': 'baking',
  'spinach': 'produce',
  'sponge': 'cleaning',
  'spring mix salad': 'produce',
  'sprinkles': 'baking',
  'starch': 'baking',
  'steak': 'meat',
  'sugar': 'baking',
  'suppres': 'medicine',
  'syrup': 'cereal',
  'tahini': 'pasta',
  'tampons': 'personal',
  'tenderloin': 'meat',
  'thyme': 'baking',
  'tilapia': 'seafood',
  'tin foil': 'soup',
  'toilet': 'cleaning',
  'diced tomat': 'beans',
  'tomato sauce': 'beans',
  'tomato soup': 'soup',
  'tomato': 'produce',
  'tonic': 'liquor',
  'tooth': 'personal',
  'tortallini': 'pasta',
  'tortellini': 'pasta',
  'tortillini': 'pasta',
  'tortilla chips': 'snacks',
  'tortillas': 'bread',
  'ground turkey': 'meat',
  'turkey': 'specialty',
  'turnip': 'produce',
  'tylenol': 'medicine',
  'veal': 'meat',
  'vegetable oil': 'baking',
  'vegetable': 'produce',
  'vinegar': 'pasta',
  'vitamin water': 'snacks',
  'vitamin': 'medicine',
  'vodka': 'liquor',
  'washer': 'cleaning',
  'weiners': 'meat',
  'whipped': 'dairy',
  'whiskey': 'liquor',
  'windex': 'cleaning',
  'wine': 'liquor',
  'wipes': 'babies',
  'yaki-soba': 'soup',
  'yakisoba': 'soup',
  'yeast': 'baking',
  'yogurt': 'dairy',
  'ziploc': 'soup',
  'zucchini': 'produce',
  // smaller catch-all words
  'baby': 'babies',
  'beans': 'beans',
  'bread': 'bread',
  'butter': 'cheese',
  'chips': 'snacks',
  'cream': 'dairy',
  'eye': 'personal',
  'face': 'personal',
  'fish': 'seafood',
  'fruit': 'produce',
  'gin': 'liquor',
  'hair': 'personal',
  'half': 'dairy',
  'ham': 'specialty',
  'kid': 'babies',
  'lip': 'personal',
  'meat': 'meat',
  'milk': 'dairy',
  'oil': 'baking',
  'pads': 'personal',
  'rum': 'liquor',
  'sauce': 'pasta',
  'soap': 'cleaning',
  'soup': 'soup',
  'tea': 'baking',
};
